---
name: "Debian / Ubuntu"

"on":
  pull_request:
    paths:
    - '.github/workflows/debian_ubuntu.yaml'
    - 'debian_ubuntu/**'

jobs:
  build-vm:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        release: ["sid", "kinetic"]

    steps:
    - uses: "actions/checkout@v2"
    - name: APT speedup
      run: |
        sudo -E eatmydata -- bash -c '
          echo update_initramfs=no >/etc/initramfs-tools/update-initramfs.conf
          : >/var/lib/dpkg/triggers/File
        '
    - name: "install dependencies"
      run: |
        sudo -E eatmydata -- bash -c '
          apt-get -qq update
          apt-get -qq install btrfs-progs debootstrap
        '
    - name: "build image"
      run: |
         sudo -E eatmydata -- ./debian_ubuntu/build_vm.sh --release ${{ matrix.release }} "$(sudo mktemp)"
