---
name: "Debian / Ubuntu"

"on":
  pull_request:
    paths:
    - 'debian_ubuntu/**'
    - '.github/workflows/debian_ubuntu.yaml'

jobs:
  build-vm:
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64", "arm64"]
        release: ["jammy", "focal", "unstable", "stable"]

    steps:
    - uses: "actions/checkout@v2"
    - name: APT speedup
      run: |
        sudo -E eatmydata -- bash -c '
          echo update_initramfs=no >/etc/initramfs-tools/update-initramfs.conf
          : >/var/lib/dpkg/triggers/File
        '
    - name: "install dependencies"
      run: |
        sudo -E eatmydata -- bash -c '
          apt-get -qq update
          apt-get -qq install --no-install-recommends --no-install-suggests btrfs-progs debootstrap qemu-user-static
        '
    - name: "build image"
      run: |
         sudo -E eatmydata -- ./debian_ubuntu/build_vm.sh --arch ${{ matrix.arch }} --release ${{ matrix.release }} "$(sudo mktemp)"
