---
name: "static-code-analysis"

"on":
  pull_request:
    paths:
    - 'debian_ubuntu/**'
    - '.github/workflows/static-code-analysis.yaml'

jobs:
  static-code-analysis:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "install dependencies"
      run: |
        sudo -E eatmydata -- bash -c '
          curl -sSLf https://github.com/mvdan/sh/releases/download/v3.4.2/shfmt_v3.4.2_linux_amd64 >/usr/local/bin/shfmt
          curl -sSLf https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz | tar -Jx shellcheck-v0.8.0/shellcheck --to-stdout >/usr/local/bin/shellcheck
          chmod 0755 /usr/local/bin/*
        '
    - name: "run static code analysis"
      run: |
        find . -name '*.sh' | grep -vFf ./.shellcheck_exclusions | xargs shellcheck --format=gcc --enable=all --exclude=SC1090,SC1091,SC2250,SC3043
        find . -name '*.sh' | grep -vFf ./.shellcheck_exclusions | xargs shfmt -d -i 2 -bn -ci
